---

ssh_port: 2222
app_name: blog
db_name: "{{ app_name }}_{{ rails_env }}"
deploy_user: "{{ app_name }}_deploy"
sites_dir: /var/www
rails_env: production
aws_s3_backup_bucket: aws-bucket-name-here
ruby_version: 2.2.2
domain_name: example.com

packages:
  - unzip
  - update-notifier-common
  - tree
  - htop
  - vim
  - tmux
  - mc

rails_dependencies:
  - nginx
  - git-core
  - curl
  - build-essential
  - nodejs
  - zlib1g-dev
  - libssl-dev
  - libreadline-dev
  - libxml2-dev
  - libcurl4-openssl-dev
  - libxslt-dev
