---

- name: Add postgres repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'

- name: Add postgres repository key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add nginx ppa
  apt_repository: repo='ppa:nginx/stable'

- name: Add tmux ppa
  apt_repository: repo='ppa:pi-rho/dev'

- name: Update apt cache
  apt: update_cache=yes
