---

- name: Install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv
    update: yes
  sudo_user: "{{ deploy_user }}"

- name: Install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
    update: yes
  sudo_user: "{{ deploy_user }}"

- name: Copy deploy user settings
  template:
    src: deploy_user_settings.j2
    dest: "/home/{{ deploy_user }}/.deploy_user_settings"
  sudo_user: "{{ deploy_user }}"

- name: Enable deploy user settings
  lineinfile:
    dest: ~/.bashrc
    line: ". ~/.deploy_user_settings"
    insertbefore: BOF
    state: present
  sudo_user: "{{ deploy_user }}"

- name: Check if your ruby version is installed
  shell: "cd ~ ; bash -lic 'rbenv versions | grep {{ ruby_version }}'"
  sudo_user: "{{ deploy_user }}"
  ignore_errors: True
  register: ruby_installed
  changed_when: false

- name: Install ruby version
  shell: "cd ~ ; bash -lic 'CONFIGURE_OPTS=--disable-install-rdoc rbenv install -s {{ ruby_version }}'"
  async: 900
  poll: 5
  sudo_user: "{{ deploy_user }}"
  when: ruby_installed.rc != 0

- name: Set global ruby version
  shell: "cd ~ ; bash -lic 'rbenv global {{ ruby_version }}'"
  sudo_user: "{{ deploy_user }}"
  when: ruby_installed.rc != 0

- name: Install bundler gem
  shell: cd ~ ; bash -lic 'gem install bundler --no-ri --no-rdoc'
  sudo_user: "{{ deploy_user }}"
  when: ruby_installed.rc != 0

- name: Run rbenv rehash
  shell: cd ~ ; bash -lic 'rbenv rehash'
  sudo_user: "{{ deploy_user }}"
  when: ruby_installed.rc != 0
